blockExoticSubdeps: false
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@5.7.2
  - volar-service-pug@0.0.71

packages:
  - extensions/*
  - packages/*
  - test-workspace

allowBuilds:
  '@vscode/vsce-sign': true
  dprint: true
  keytar: true
