packages:
  - extensions/*
  - extensions/vscode/e2e/workspace
  - packages/*
  - test-workspace

onlyBuiltDependencies:
  - '@tsslint/core'
  - '@tsslint/eslint'
  - '@vscode/vsce-sign'
  - dprint
  - esbuild
  - keytar
  - rolldown
