blockExoticSubdeps: false
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - extensions/*
  - packages/*
  - test-workspace

allowBuilds:
  '@vscode/vsce-sign': true
  dprint: true
  keytar: true
