import type { ComponentMeta } from '../../../component-meta';

// taken from `test-workspace/tsc/hover/child.vue`
// @ts-expect-error - apparently the real object is not compatible with the type
export const mockComponentMeta = {
	type: 1,
	props: [
		{
			name: 'requiredProp',
			global: false,
			description: 'This is a requird prop',
			tags: [
				{
					name: 'foo',
					text: 'This is a custom tag',
				},
			],
			required: true,
			type: 'string',
			schema: 'string',
			declarations: [],
		},
		{
			name: 'withDefault',
			global: false,
			default: 'false',
			description: 'This is a prop with a default value',
			tags: [],
			required: false,
			type: 'boolean | undefined',
			schema: 'boolean | undefined',
			declarations: [],
		},
		{
			name: 'justTags',
			global: false,
			description: '',
			tags: [
				{
					name: 'description',
					text:
						'A very long description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
				},
				{
					name: 'anotherDescription',
					text: `Now with multiple lines!
Lorem ipsum`,
				},
				{
					name: 'name',
					text: 'Some name',
				},
			],
			required: false,
			type: 'string | undefined',
			schema: 'string | undefined',
			declarations: [],
		},
		{
			name: 'noDescription',
			global: false,
			description: '',
			tags: [],
			required: false,
			type: 'boolean | undefined',
			schema: 'boolean | undefined',
			declarations: [],
		},
		{
			name: 'withObjectType',
			global: false,
			description: 'Object type',
			tags: [],
			required: false,
			type: '{ foo: string; bar: number; } | undefined',
			schema: '{ foo: string; bar: number; } | undefined',
			declarations: [],
		},
		{
			name: 'withMarkdown',
			global: false,
			description: `With some markdown

# Who puts a title in a jsdoc comment?

> This is a blockquote

- This is a list item
- This is another list item`,
			tags: [],
			required: false,
			type: 'string | undefined',
			schema: 'string | undefined',
			declarations: [],
		},
		{
			name: 'withCodeBlock',
			global: false,
			description: `With code block
\`\`\`ts
const foo: string = 'bar'
\`\`\``,
			tags: [],
			required: false,
			type: 'string | undefined',
			schema: 'string | undefined',
			declarations: [],
		},
		{
			name: 'deprecatedProp',
			global: false,
			description: 'This is a deprecated prop',
			tags: [
				{
					name: 'deprecated',
					text: 'This prop is deprecated and should not be used',
				},
			],
			required: false,
			type: 'string | undefined',
			schema: 'string | undefined',
			declarations: [],
		},
		{
			name: 'onSomePropEvent',
			global: false,
			description: 'Because it starts with "onX" this prop is treated as an event',
			tags: [],
			required: false,
			type: '((value: string) => void) | undefined',
			schema: '((value: string) => void) | undefined',
			declarations: [],
		},
		{
			name: 'onlyAPropStartingWithOn',
			global: false,
			description: `Because the "l" is lower case this prop will is not being treated as
an event`,
			tags: [],
			required: false,
			type: 'string | undefined',
			schema: 'string | undefined',
			declarations: [],
		},
		{
			name: 'manualModel',
			global: false,
			description: 'This is a model created without `defineModel`',
			tags: [],
			required: false,
			type: 'string | undefined',
			schema: 'string | undefined',
			declarations: [],
		},
		{
			name: 'manualModelWithPropEvent',
			global: false,
			description: 'This is a model created without `defineModel` and with a prop as an event',
			tags: [],
			required: false,
			type: 'string | undefined',
			schema: 'string | undefined',
			declarations: [],
		},
		{
			name: 'onUpdate:manualModelWithPropEvent',
			global: false,
			description: '',
			tags: [],
			required: false,
			type: '((value: string) => Promise<void>) | undefined',
			schema: '((value: string) => Promise<void>) | undefined',
			declarations: [],
		},
		{
			name: 'modelValue',
			global: false,
			description: 'This is the default model',
			tags: [],
			required: false,
			type: 'string | undefined',
			schema: 'string | undefined',
			declarations: [],
		},
		{
			name: 'requiredModel',
			global: false,
			description: 'This is a required model',
			tags: [],
			required: true,
			type: 'string',
			schema: 'string',
			declarations: [],
		},
		{
			name: 'modelWithDefault',
			global: false,
			default: '"default value"',
			description: 'This is a model with a default value',
			tags: [],
			required: false,
			type: 'string | undefined',
			schema: 'string | undefined',
			declarations: [],
		},
		{
			name: 'deprecatedModel',
			global: false,
			description: 'This is a deprecated model',
			tags: [
				{
					name: 'deprecated',
					text: 'This model is deprecated and should not be used',
				},
			],
			required: false,
			type: 'string | undefined',
			schema: 'string | undefined',
			declarations: [],
		},
		{
			name: 'key',
			global: true,
			description: '',
			tags: [],
			required: false,
			type: 'PropertyKey | undefined',
			schema: 'PropertyKey | undefined',
			declarations: [],
		},
		{
			name: 'ref',
			global: true,
			description: '',
			tags: [],
			required: false,
			type: 'VNodeRef | undefined',
			schema: 'VNodeRef | undefined',
			declarations: [],
		},
		{
			name: 'ref_for',
			global: true,
			description: '',
			tags: [],
			required: false,
			type: 'boolean | undefined',
			schema: 'boolean | undefined',
			declarations: [],
		},
		{
			name: 'ref_key',
			global: true,
			description: '',
			tags: [],
			required: false,
			type: 'string | undefined',
			schema: 'string | undefined',
			declarations: [],
		},
		{
			name: 'onVue:beforeMount',
			global: true,
			description: '',
			tags: [],
			required: false,
			type: 'VNodeMountHook | VNodeMountHook[] | undefined',
			schema: 'VNodeMountHook | VNodeMountHook[] | undefined',
			declarations: [],
		},
		{
			name: 'onVue:mounted',
			global: true,
			description: '',
			tags: [],
			required: false,
			type: 'VNodeMountHook | VNodeMountHook[] | undefined',
			schema: 'VNodeMountHook | VNodeMountHook[] | undefined',
			declarations: [],
		},
		{
			name: 'onVue:beforeUpdate',
			global: true,
			description: '',
			tags: [],
			required: false,
			type: 'VNodeUpdateHook | VNodeUpdateHook[] | undefined',
			schema: 'VNodeUpdateHook | VNodeUpdateHook[] | undefined',
			declarations: [],
		},
		{
			name: 'onVue:updated',
			global: true,
			description: '',
			tags: [],
			required: false,
			type: 'VNodeUpdateHook | VNodeUpdateHook[] | undefined',
			schema: 'VNodeUpdateHook | VNodeUpdateHook[] | undefined',
			declarations: [],
		},
		{
			name: 'onVue:beforeUnmount',
			global: true,
			description: '',
			tags: [],
			required: false,
			type: 'VNodeMountHook | VNodeMountHook[] | undefined',
			schema: 'VNodeMountHook | VNodeMountHook[] | undefined',
			declarations: [],
		},
		{
			name: 'onVue:unmounted',
			global: true,
			description: '',
			tags: [],
			required: false,
			type: 'VNodeMountHook | VNodeMountHook[] | undefined',
			schema: 'VNodeMountHook | VNodeMountHook[] | undefined',
			declarations: [],
		},
		{
			name: 'class',
			global: true,
			description: '',
			tags: [],
			required: false,
			type: 'unknown',
			schema: 'unknown',
			declarations: [],
		},
		{
			name: 'style',
			global: true,
			description: '',
			tags: [],
			required: false,
			type: 'unknown',
			schema: 'unknown',
			declarations: [],
		},
	],
	events: [
		{
			name: 'update:modelValue',
			description: '',
			tags: [],
			type: '[value: string | undefined]',
			signature: '(event: "update:modelValue", value: string | undefined): void',
			schema: [
				'string | undefined',
			],
			declarations: [],
		},
		{
			name: 'update:requiredModel',
			description: '',
			tags: [],
			type: '[value: string]',
			signature: '(event: "update:requiredModel", value: string): void',
			schema: [
				'string',
			],
			declarations: [],
		},
		{
			name: 'update:modelWithDefault',
			description: '',
			tags: [],
			type: '[value: string]',
			signature: '(event: "update:modelWithDefault", value: string): void',
			schema: [
				'string',
			],
			declarations: [],
		},
		{
			name: 'update:deprecatedModel',
			description: '',
			tags: [],
			type: '[value: string | undefined]',
			signature: '(event: "update:deprecatedModel", value: string | undefined): void',
			schema: [
				'string | undefined',
			],
			declarations: [],
		},
		{
			name: 'customEvent',
			description: '',
			tags: [],
			type: '[]',
			signature: '(event: "customEvent"): void',
			schema: [],
			declarations: [],
		},
		{
			name: 'eventWithPayload',
			description: '',
			tags: [],
			type: '[payload: string, payload2: number]',
			signature: '(event: "eventWithPayload", payload: string, payload2: number): void',
			schema: [
				'string',
				'number',
			],
			declarations: [],
		},
		{
			name: 'deprecatedEvent',
			description: '',
			tags: [],
			type: '[]',
			signature: '(event: "deprecatedEvent"): void',
			schema: [],
			declarations: [],
		},
		{
			name: 'update:manualModel',
			description: '',
			tags: [],
			type: '[value: string]',
			signature: '(event: "update:manualModel", value: string): void',
			schema: [
				'string',
			],
			declarations: [],
		},
	],
	slots: [
		{
			name: 'default',
			type: 'any',
			description: 'This is a default slot',
			tags: [],
			schema: 'any',
			declarations: [],
		},
		{
			name: 'slotWithProps',
			type: '{ foo: string; }',
			description: 'This is a slot with props',
			tags: [],
			schema: '{ foo: string; }',
			declarations: [],
		},
		{
			name: 'deprecatedSlot',
			type: 'any',
			description: 'This is a deprecated slot',
			tags: [
				{
					name: 'deprecated',
					text: 'This slot is deprecated and should not be used',
				},
			],
			schema: 'any',
			declarations: [],
		},
	],
	exposed: [
		{
			name: 'exposedMethod',
			type: '() => void',
			description: 'This is a method that can be called from the parent component',
			tags: [],
			schema: '() => void',
			declarations: [],
		},
		{
			name: 'exposedProperty',
			type: 'string',
			description: 'This is a property that can be accessed from the parent component',
			tags: [],
			schema: 'string',
			declarations: [],
		},
	],
} as ComponentMeta;
