export * from './generators/template';
export * from './languageModule';
export * as scriptRanges from './parsers/scriptRanges';
export * as scriptSetupConvertRanges from './parsers/scriptSetupConvertRanges';
export * from './parsers/scriptSetupRanges';
export * from './plugins';
export * from './sourceFile';
export * from './types';
export * as localTypes from './utils/localTypes';
export * from './utils/ts';
export * from './utils/parseSfc';
