const raw = {
	export: '',
	components: '',
	ctx: '',
	defaultModels: '',
	defaults: '',
	directives: '',
	dollars: '',
	emit: '',
	exposed: '',
	intrinsics: '',
	modelEmit: '',
	props: '',
	setup: '',
	slots: '',
	src: '',

	Emit: '',
	EmitProps: '',
	GlobalComponents: '',
	InheritedAttrs: '',
	LocalComponents: '',
	LocalDirectives: '',
	ModelEmit: '',
	ModelProps: '',
	Props: '',
	PublicProps: '',
	RootEl: '',
	SetupExposed: '',
	Slots: '',
	StyleModules: '',
	StyleScopedClasses: '',
	TemplateRefs: '',

	// #region template helpers
	asFunctionalComponent0: '',
	asFunctionalComponent1: '',
	asFunctionalDirective: '',
	asFunctionalElement0: '',
	asFunctionalElement1: '',
	asFunctionalSlot: '',
	directiveBindingRestFields: '',
	functionalComponentArgsRest: '',
	tryAsConstant: '',
	vFor: '',
	vSlot: '',

	ConstructorOverloads: '',
	Elements: '',
	EmitsToProps: '',
	FunctionalComponent0: '',
	FunctionalComponent1: '',
	FunctionalComponentCtx: '',
	FunctionalComponentProps: '',
	IsAny: '',
	IsFunction: '',
	NormalizeComponentEvent: '',
	NormalizeEmits: '',
	OverloadUnion: '',
	OverloadUnionInner: '',
	PickNotAny: '',
	PrettifyGlobal: '',
	ResolveDirectives: '',
	ResolveEmits: '',
	ShortEmits: '',
	ShortEmitsToObject: '',
	SpreadMerge: '',
	UnionToIntersection: '',
	WithComponent: '',
	// #endregion
};

export const names = Object.fromEntries(
	Object.keys(raw).map(key => [key, `__VLS_${key}`]),
) as typeof raw;
