const raw = {
	base: '',
	export: '',
	components: '',
	componentsOption: '',
	ctx: '',
	defaultModels: '',
	defaults: '',
	directives: '',
	directivesOption: '',
	dollars: '',
	emit: '',
	exposed: '',
	intrinsics: '',
	modelEmit: '',
	props: '',
	propsOption: '',
	self: '',
	setup: '',
	slots: '',
	src: '',

	Emit: '',
	EmitProps: '',
	GlobalComponents: '',
	InheritedAttrs: '',
	LocalComponents: '',
	LocalDirectives: '',
	ModelEmit: '',
	ModelProps: '',
	Props: '',
	PublicProps: '',
	RootEl: '',
	RootChildren: '',
	rootChildrenId: '',
	RootIdentity: '',
	SetupExposed: '',
	Slots: '',
	StyleModules: '',
	StyleScopedClasses: '',
	TemplateRefs: '',

	SlotComponentProps: '',
	SlotElement: '',
	SlotChild: '',
	SlotReturn: '',
	SlotReturns: '',
	ExpandSlotOutlet: '',
	ExpandSlotChild: '',
	ExpandSlotChildren: '',

	// #region template helpers
	asFunctionalComponent0: '',
	asFunctionalComponent1: '',
	asFunctionalDirective: '',
	asFunctionalElement0: '',
	asFunctionalElement1: '',
	asFunctionalSlot: '',
	componentSlotChildren: '',
	componentSlotIdentity: '',
	directiveBindingRestFields: '',
	functionalComponentArgsRest: '',
	omit: '',
	tryAsConstant: '',
	vFor: '',
	vSlot: '',

	ConstructorOverloads: '',
	Elements: '',
	EmitsToProps: '',
	FunctionalComponent0: '',
	FunctionalComponent1: '',
	FunctionalComponentCtx: '',
	FunctionalComponentProps: '',
	IsAny: '',
	IsFunction: '',
	NormalizeEmits: '',
	OverloadUnion: '',
	OverloadUnionInner: '',
	PickNotAny: '',
	PrettifyGlobal: '',
	ResolveDirectives: '',
	ResolveEmits: '',
	ResolveEvent: '',
	ShortEmits: '',
	ShortEmitsToObject: '',
	SpreadMerge: '',
	UnionToIntersection: '',
	WithComponent: '',
	// #endregion
};

export const names = Object.fromEntries(
	Object.keys(raw).map(key => [key, `__VLS_${key}`]),
) as typeof raw;
